version: '3'
services:
  client:
    build:
      context: ./etc
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./diagrams:/diagrams
    depends_on:
      - drawio
      - server
  server:
    build:
      context: ./etc
      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - ./diagrams:/diagrams
  drawio:
    build:
      context: ./etc
      dockerfile: Dockerfile-drawio
    ports:
      - "8080:8080"
